---
- hosts: all
  tasks:
    - copy:
        src: xinitrc
        dest: /home/g/.xinitrc
        owner: g
        group: users

    - copy:
        src: xprofile
        dest: /home/g/.xprofile
        owner: g

    - copy:
        src: zshrc
        dest: /home/g/.zshrc
        owner: g
        group: users

    - copy:
        src: xprofile
        dest: /home/g/.xprofile
        owner: g
        group: users

    - copy:
        src: psmouse.conf
        dest: /etc/modprobe.d/psmouse.conf
        owner: root
        group: root
      become: yes

    - copy:
        src: 70-synaptics.conf
        dest: /etc/X11/xorg.conf.d
        owner: root
        group: root
      become: yes

    - copy:
        src: "{{ item }}"
        dest: /usr/local/bin
        owner: g
        group: users
        mode: u+x
      with_items:
        - bin/dwm-brightness
        - bin/dwm-bar
        - bin/dwm-bar-restart
        - bin/screengrab
        - bin/screengrab-select
        - bin/screen-lock
      become: yes

    - pacman: 
        name: 
          - xorg-server
          - xorg-xinit
          - libxft
          - libxinerama
          - firefox
          - dmenu
          - alsa-utils
          - light
          - zsh
          - acpi
          - xorg-xsetroot
          - feh
          - bluez-utils
          - bluez
          - xorg-xrandr
          - nvidia
          - compton
          - telegram-desktop
          - redshift
          - pulseaudio
          - pulseaudio-bluetooth
          - pulseaudio-alsa
          - mplayer
          - zsh
          - tree
          - ruby
          - chromium
          - maim
          - ttf-droid # switch chromium to use this font for proper pdf rendering
          # printing: sudo systemctl enable org.cups.cupsd.service
          # sudo systemctl start org.cups.cupsd.service
          - cups
          - cups-pdf # print to pdf
          - hplip # hp drivers - then run sudo hp-setup -i 
          - unzip
          - aria2
          - vlc
          - xautolock
          - nmap
          - autojump
          - exfat-utils # sdcard  mount
          - ctags
          - vault
          - jq
          - recordmydesktop
          - xf86-input-synaptics
        state: present
      become: yes


    - lineinfile:
        path: /etc/bluetooth/main.conf
        regexp: "^AutoEnable="
        line: AutoEnable=true
      become: yes

    # allows laptop lid to be closed
    - lineinfile:
        path: /etc/systemd/logind.conf
        regexp: "^HandleLidSwitchExternalPower"
        line: HandleLidSwitchExternalPower=ignore
      become: yes


    
