---
- hosts: all
  become: yes
  tasks:
    - file: 
        path: /etc/systemd/resolved.conf.d 
        state: directory
        mode: '0755'
    - copy:
        src: dns_servers.conf
        dest: /etc/systemd/resolved.conf.d/dns_servers.conf
        owner: root
        group: root
    - systemd:
        state: started
        name: systemd-resolved

