---
- hosts: all
  tasks:
    - pacman: 
        name: 
          - maven
          - python-pip
          - python-virtualenv
        state: present
      become: yes
    - pip:
        name: 
          - ansible[azure]

