#!/bin/sh

compton &

/usr/local/bin/dwm-bar &

feh --bg-fill /home/g/Downloads/wp3067724-the-expanse-wallpapers.png &

xset r rate 200 30 &

xautolock -time 5 -locker screen-lock &

xrdb ~/.Xresources
