#!/bin/sh

compton --vsync --backend glx &
xrdb ~/.Xresources
xset r rate 200 30 &
xsetroot -cursor_name left_ptr
xautolock -time 15 -locker screen-lock &
feh --bg-fill /home/g/Downloads/pexels-aleksandar-pasaric-325185.jpg


/usr/local/bin/dwm-bar &

#/home/g/.config/polybar/launch.sh 
#sxhkd&

# gets rid of error message associated with starting
# pavucontrol (GTK+ errors)
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

st &
st &
