#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

mainmonitor="$(bspc query --monitors --names | grep -v eDP1 | head -n 1)"

#if ! echo "$mainmonitor" | grep eDP1 >/dev/null 2>&1; then
#    xrandr --output "$mainmonitor" --auto --output eDP1 --off
#fi

# Start workspaces on the main monitor.
bspc monitor $mainmonitor -d 1 2 3 4 5 6 7 8 9 10

bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI-0 -d I II III IV V
bspc monitor eDP-1-1 -d I II III IV V

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
